### ISSUE TITLE
Fix perms

### ISSUE THREAD

**Issue by hube12** [minecrafthome/minecraft-beta-alpha-terrain-generation-cpp#3]
Total 5 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
To https://github.com/minecrafthome/minecraft-beta-alpha-terrain-generation-cpp.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/minecrafthome/minecraft-beta-alpha-terrain-generation-cpp.git'

**Comment by ChipWolf** [comment]
@hube12 removed the branch permissions
